version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # location of your package.json
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "react" 
        versions: ["<18.0.0"]
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
